name: 'Push image to AWS ECR Registry'
description: 'Build and push Docker image to AWS ECR registry'
inputs:
  ecr-access-key: 
    description: 'AWS Access Key to access to ECR'
    required: true
  ecr-secret-key:  
    description: 'AWS Secret Key to access to ECR'
    required: true
  docker-registry: 
    description: 'Docker registry'
    required: true
    default: 'ghcr.io'
  docker-image: 
    description: 'Docker image name'
    required: true
runs:
  using: "composite"
  steps:
    - 
      name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v1

    - name: Login to Amazon ECR
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.docker-registry }}
        username: ${{ inputs.ecr-access-key }}
        password: ${{ inputs.ecr-secret-key }}

    - name: Prepare docker image name
      id: image_names
      run: |
        IMAGES="${{ inputs.docker-registry }}/${{ inputs.docker-image }}"
        echo ::set-output name=images::${IMAGES}
      shell: bash

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ steps.image_names.outputs.images }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha

    - name: Build & Push image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        cache-from: type=gha, scope=${{ github.workflow }}
        cache-to: type=gha, scope=${{ github.workflow }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
  